config_directory: /build_config
artifact_directory: /build_artifact
explode_directory: /build_explode
artifact_server: http://artifact.infrabuild.xyz
vsphere:
  vcenter_server: vcenter.infrabuild.xyz
  cluster: main
  datacenter: Datacenter
  datastore: Datastore1
  folder: Templates
  network: BUILDNET
  username: administrator@vsphere.infrabuild.xyz
  password: DunderMifflin1234$
  esxi_hostname: 192.168.5.202
rhsm:
  username: redhat_username
  password: BadPassword1234$
  pool_id: 769a77667d83243s769a77667d83243s
env:
  VMWARE_PASSWORD: "{{ vsphere.password }}"
  RHSM_PASSWORD: "{{ lookup('env', 'RHSM_PASSWORD') }}"
  PACKER_CACHE_DIR: "{{ artifact_directory }}"
  PACKER_LOG: 1
  PACKER_LOG_PATH: "{{ artifact_directory }}/packerlog.txt"
#False will only generate config file but not run build
run_build: false
#Default build filter (use everything)
build_filter:
- vyos
- pfsense
- kali
- esxi
- centos7
- centos8
- rhel7
- rhel8
batch_size: 2
#Filter out any build not specified in the build_filter so you only build what you want
active_config: "{{ build_list | selectattr('build_name', 'in', build_filter) | list }}" 
#Make a comman seperated list of the build names within the active build
active_build: "{{ active_config | map(attribute='packer_file.builders') | flatten | map(attribute='name') | list | join(',') }}"
#This is probably unnecessary now since we don't individually sort build vs config
#active_build_dict: "{{ active_config | selectattr('should_build', 'eq', 'build') | list }}"
config_files: "{{ active_config | selectattr('files', 'defined') | map(attribute='files') | list | flatten | unique }}"
packer_all:
  variables: "{{ active_config | selectattr('packer_file.variables', 'defined') | map(attribute='packer_file.variables') | list | combine }}"
  sensitive-variables: "{{ active_config | selectattr('packer_file.sensitive-variables', 'defined') | map(attribute='packer_file.sensitive-variables') | list | flatten | unique }}"
  builders: "{{ active_config | selectattr('packer_file.builders', 'defined') | map(attribute='packer_file.builders') | list | flatten }}"
  provisioners: "{{ active_config | selectattr('packer_file.provisioners', 'defined') | map(attribute='packer_file.provisioners') | list | flatten }}"
ddmmyy: "{{ lookup('pipe','date +%d%m%y') }}"
